name: "Code Scanning - Action"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # Override language selection by uncommenting this and choosing your languages
        # with:
        #   languages: go, javascript, csharp, python, cpp, java

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).

      # [START] Set up the environment for Linux
      - name: Updating the packages list
        run: sudo apt update
      - name: Upgrading the packages
        run: sudo apt upgrade
      - name: Installing the build-essential package
        run: sudo apt install build-essential
      - name: Validating the GCC compiler
        run: gcc --version
      # [END] Set up the environment for Linux

      - name: List files in the compiler dir
        run: ls ${{ github.workspace }}/compiler/
      - name: Building the compiler
        run: |
          cd compiler
          gcc -g start.c -o GitHubBuild_Mur_Linux.out -lm
      - name: Delete "Mur.out"
        run: rm ${{ github.workspace }}/compiler/Mur.out
      - name: Delete "Mur.exe"
        run: rm ${{ github.workspace }}/compiler/Mur.exe
      - name: List files in the compiler dir
        run: ls ${{ github.workspace }}/compiler/

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #   make bootstrap
      #   make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
