name: Docs Builds (Docusaurus)
on: [push, pull_request]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # [START] Set up the environment
      - name: Updating the packages list
        run: sudo apt update
      - name: Installing NodeJS
        run: sudo apt install nodejs
      - name: Installing NPM
        run: sudo apt install npm
      - name: Installing some npm packages
        run: |
          cd docusaurus
          npm install
      #yarn run write-translations -- --locale ar
      #mkdir i18n\ar\docusaurus-plugin-content-docs\current\
      #copy docs\** i18n\ar\docusaurus-plugin-content-docs\current\
      #mkdir i18n\ar\docusaurus-plugin-content-blog\
      #copy blog\** i18n\ar\docusaurus-plugin-content-blog\
      #mkdir i18n\ar\docusaurus-plugin-content-pages\
      #copy src\pages\**.md i18n\ar\docusaurus-plugin-content-pages\
      #copy src\pages\**.mdx i18n\ar\docusaurus-plugin-content-pages\
      # [END] Set up the environment

      - name: Building the docs website
        run: |
          cd docusaurus
          npm run build
      - name: List files in the build dir
        run: ls ${{ github.workspace }}/docusaurus/build/
      - run: echo "This job's status is ${{ job.status }}."
